# Generated by Django 3.0.8 on 2020-09-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20200924_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='finished',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='started',
            field=models.DateField(blank=True, null=True),
        ),
    ]
