# Generated by Django 3.0.8 on 2020-09-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20200924_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='timeplayed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
