# Generated by Django 3.0.8 on 2020-10-15 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20200924_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlaytime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.IntegerField()),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diary.Entry')),
            ],
        ),
    ]
