# Generated by Django 3.0.8 on 2020-10-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_dailyplaytime'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='stoppedplaying',
            field=models.DateField(blank=True, null=True),
        ),
    ]
